export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const GET_INITIAL_DATA_SUCCESS = 'GET_INITIAL_DATA_SUCCESS';
export const GET_INITIAL_DATA_ERROR = 'GET_INITIAL_DATA_ERROR';
export const VERIFY_WITH_VERID = 'VERIFY_WITH_VERID';
export const VERID_VERIFIED = 'VERID_VERIFIED';
export const VERID_VERIFIED_ERROR = 'VERID_VERIFIED_ERROR';
