export const GET_USER_DATA = 'GET_USER_DATA';
export const SAGA_SUCCESS = 'SAGA_SUCCESS';
export const SAGA_ERROR = 'SAGA_ERROR';

export const IS_DOC_SIGNED = 'IS_DOC_SIGNED';
export const SAGA_DOCUSIGN_SUCCESS = 'SAGA_DOCUSIGN_SUCCESS';
export const SAGA_DOCUSIGN_ERROR = 'SAGA_DOCUSIGN_ERROR';
export const SAGA_IS_DOCUSIGN_SUCCESS = 'SAGA_IS_DOCUSIGN_SUCCESS';
export const SAGA_IS_DOCUSIGN_ERROR = 'SAGA_IS_DOCUSIGN_ERROR';
