export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const SEND_NEW_USER_RESPONSE = 'SEND_NEW_USER_RESPONSE';
export const SAVE_USER_SAGA_ERROR = 'SAVE_USER_SAGA_ERROR';
export const SAVE_USER_SAGA_SUCCESS = 'SAVE_USER_SAGA_SUCCESS';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_RESPONSE = 'AUTHENTICATE_USER_RESPONSE';
export const AUTHENTICATE_USER_RESPONSE_ERROR = 'AUTHENTICATE_USER_RESPONSE_ERROR';


